#!/usr/bin/env bash
#This is a bash script that loops from 1 to 10 and displays bad luck on the 4th loop iteration, displays good luck for the 8th iteration and displays Best School for the other iterations
x=1
while [ $x -le 8 ]
do
	echo "Best School"
	if [ $x == 3 ]
	then
		echo "bad luck"
	elif [ $x == 6 ]
	then
		echo "good luck"
	else
		true
	fi
	x=$(( x + 1 ))
done
