#!/usr/bin/env bash
#This script will display the contents of the current directory in a list format where only the part of the name after the first dash is displayed using the for loop

list=$(ls)
for list in $list
do
	echo "$list" | rev | cut -d '-' -f1 | rev
done
